In [1]:
import numpy as np
import pandas as pd

### Matrix Multiplication

In [14]:
def matgen3d():
    """
    Function to generate a random integer 3x3 matrix
    Min value: 1, Max value: 9
    """
    return np.random.randint(low=0, high=10, size=(3,3))

mat1 = matgen3d()
mat2 = matgen3d()

print("First matrix:\n", mat1)
print()
print("Second matrix:\n", mat2)
print()
print("Product of the two matrix")
print(np.matmul(mat1, mat2))

First matrix:
 [[4 3 3]
 [2 4 2]
 [0 1 4]]

Second matrix:
 [[4 8 1]
 [0 2 3]
 [6 6 2]]

Product of the two matrix
[[34 56 19]
 [20 36 18]
 [24 26 11]]
